[GLOBAL]
pants_version = "2.9.0.dev3"
backend_packages = [
  "pants.backend.python",
]
pantsd_max_memory_usage = "4GiB"

[python]
interpreter_constraints = [">=3.8,<3.9"]
requirement_constraints = "pants-requirements.txt"

[python-infer]
inits = true

[source]
marker_filenames = ["SOURCE_ROOT"]

[anonymous-telemetry]
enabled = false

[python-repos]
indexes = [
    "https://pypi.org/simple/",
  ]

[pytest]
execution_slot_var = "PANTS_EXECUTION_SLOT"

[subprocess-environment]
env_vars = [
    "LA_LIBRARY_FILEPATH",
]

[test]
xml_dir = "dist/.test_results/"

extra_env_vars = [
    "TMPDIR",
    "LANG",
    "LC_CTYPE",
    "LC_ALL",
    "SRC_ROOT",
]

[cli.alias]
deps = "dependencies --dependencies-closed"
tdeps = "dependencies --dependencies-transitive --dependencies-closed"
depe = "dependees --dependees-closed"
tdepe = "dependees --dependees-transitive --dependees-closed"
ft = "filter --target-type=python_tests"

[stats]
log = false
